<a href="https://colab.research.google.com/github/MyatnyjChaj3/-_-_-_-_-_6-/blob/master/practise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = 'presentation'

"""
Практическая 2 v2. Комплексная экспонента.
Слайд 2
"""
N = 128
n = np.arange(N)
x = 2*np.cos(0.2*n+0.1)+3*np.cos(0.2*n-0.35)
#x = 2*np.real(np.exp())

xx = 4.879*np.cos(0.2*n-0.17)


fig = go.Figure()
fig.add_scatter( y = x, mode='lines', line_width=1.5 )
fig.add_scatter( y = xx, mode='lines', line_width=1.5 )
fig.update_layout( xaxis_title=r'$n$', yaxis_title=r'$x(n)$' )
fig.update_layout(
    title=dict(text='Сумма косинусоид',font=dict(size=18))
    )
fig.update_xaxes(gridcolor="lightgray",dtick=25,showgrid=True)
fig.update_yaxes(gridcolor="lightgray",dtick=2,showgrid=True)
fig.show()


$2\cos(0.2n +0.1) + 3*cos(0.2n - 0.35) =Re(2*e^{i(0.2n+0.1)}) + Re(3*e^{i(0.2n - 0.35)}) = Re(2*e^{i0.1}*e^{0.2n}) + Re(3*e^{-i0.35}*e^{0.2n}) = Re(2*e^{i0.1}*e^{i0.2n} + 3*e^{-i0.35}*e^{i0.2n}) = Re((2*e^{i0.1} + 3*e^{-i0.35})*e^{i0.2n})$

In [ ]:
F = 2*np.exp(1j*0.1)+3*np.exp(1j*(-0.35))
print(np.abs(F))
print(np.angle(F))

4.879074218356606
-0.17074314246335998


In [ ]:
import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = 'presentation'

"""
Практическая 2 v2. Комплексная экспонента.
Слайд 2
"""
N = 128
n = np.arange(N)
x = 2*np.cos(0.2*n+0.1)+3*np.cos(0.2*n-0.35)
#x = 2*np.real(np.exp())

xx = 4.879*np.cos(0.2*n-0.17)
x1 =

fig = go.Figure()
fig.add_scatter( y = x, mode='lines', line_width=1.5 )
fig.add_scatter( y = xx, mode='lines', line_width=1.5 )
fig.update_layout( xaxis_title=r'$n$', yaxis_title=r'$x(n)$' )
fig.update_layout(
    title=dict(text='Сумма косинусоид',font=dict(size=18))
    )
fig.update_xaxes(gridcolor="lightgray",dtick=25,showgrid=True)
fig.update_yaxes(gridcolor="lightgray",dtick=2,showgrid=True)
fig.show()


$y(n)=\sum\limits_{m=0}^{M-1}h(m)x(n-m)$

In [ ]:
x = [1,2,3,4,5]
h = [1,2,3]
y1 = np.convolve(h,x,mode='valid')
y2 = np.convolve(h,x,mode='same')
y3 = np.convolve(h,x,mode='full')
print(y1)
print(y2)
print(y3)

[10 16 22]
[ 4 10 16 22 22]
[ 1  4 10 16 22 22 15]
